### PR TITLE
third commit

### PR DESCRIPTION
**Pull request by Jaybabaa**
Hello. Please review. The images that were not put in a file concerning the assets folder are that way because if I do put them in a file they break my code. if you have a way around it, I would not mind editing my code. Thank you.

### CODE REVIEW

**Review by ifr4h — COMMENTED** [review]
Hey, so I have managed to fix the image problem. Please double-check it works on your console as well. It probably didn't work due to one or more of the following issues.

- Missing a backslash when directing the images i.e assets/images/wine.jpg is missing the folder name so it should be assets/images/homepage/wine.jpg
- Make sure you are targeting the correct images. It took me a while to display the "explore categories" images. This was because the images are stored in a js file, not the index.html

The page looks really good, but I noticed you are using a CSS file outside of the stylesheets folder. To clean up to code, you can paste all your code into the _homepage.scss file. 

-  To find this stylesheet click on the stylesheet folder, then the pages folder and it should be there.
- Don't forget to change this in your HTML so the source should be stylesheets/styles.css and note stylesheets/index.css

**Comment by Jaybabaa** [comment]
The images stored in the js file are url links of images for the testimonial.

**Comment by Jaybabaa** [comment]
styles.css is already used to the brim and there are media selectors for responsiveness there. Yes, the landing page is meant to be linked to style.css but it was already used.

**Comment by Jaybabaa** [comment]
I will put more focus now on organizing the images properly in the assets folder

**Comment by Jaybabaa** [comment]
I deleted the index.css and merged my css into the styles.css

**Comment by Jaybabaa** [comment]
All changes have been positively effected.

**Comment by Jaybabaa** [comment]
Please do the final review. Thank you.

**Comment by ifr4h** [comment]
Please move your CSS to the _homepage.scss file. The styles.css should never be manually edited since we are using sass. The styles.css is the complied file with all the sass files.

**Comment by ifr4h** [comment]
Once you have done that, you should be ready to merge your work

**Comment by Jaybabaa** [comment]
I did move it to _homepage.scss file and it broke my code. Maybe it’s cause it is pure CSS. I think it’s best I create a css file under Spreadsheets folder.

**Comment by Jaybabaa** [comment]
That's really not feasible please. The Css codes that Sass didn't pick up are the ones that are not compatible with Sass right now. if i take them to any Css file, they work just fine. Telling me to refactor my code on a sass file when I haven't any knowledge of sass is just somehow. I feel you should reconsider and we proceed with my current skills. Thank you.

**Pull request merged**
